#!/usr/bin/env bash

# Update package lists and install Nginx
sudo apt update
sudo apt install -y nginx

# Define the custom header configuration
custom_header_conf="\
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    location / {
        add_header X-Served-By \$hostname;
        # Other Nginx configuration directives can go here if needed
    }
}"

# Create a new configuration file for the custom header
sudo bash -c "echo '$custom_header_conf' > /etc/nginx/sites-available/custom_header"

# Create a symbolic link to enable the custom header configuration
sudo ln -s /etc/nginx/sites-available/custom_header /etc/nginx/sites-enabled/

# Test Nginx configuration and restart Nginx
sudo nginx -t && sudo systemctl restart nginx
